### ISSUE TITLE
définition du protocole de communication

### ISSUE THREAD

**Issue by SteveRuben** [hehchain/callo#3]
En se basant sur le protocole de telegram [here](https://core.telegram.org/mtproto) définir un protocole de communication pour les nœuds dans le réseau. 
Sachant que les informations dans le réseau sont chiffrés et qu'il faut avoir une clé privée pour connaitre le contenu du message et même la source du message.

**Comment by SteveRuben** [comment]
produire une documentation ( un ficher d'extension md) @alexzebaze

**Comment by SteveRuben** [comment]
@feav  tu n'as pas finir ceci.

**Comment by feav** [comment]
@Tryptich  j ai créé la branche "**WIP#2**" OU J AI INTRODUIT LE FICHIER MD CONSERNANT LA PREMIERE VERSION DU PROTOCOLE DE COMMUNICATION DANS LE RESEAU [LIEN DU PROTOCOLE DE COMMUNICATION VERSION 1](https://github.com/hehchain/callo/blob/WIP%232/docs/protocole%20de%20communication.md)

**Comment by SteveRuben** [comment]
Ok

Provenance : Courrier pour Windows 10

De : armel embolo
Envoyé le :samedi 30 décembre 2017 07:36
À : hehchain/callo
Cc : Steve Ruben; Mention
Objet :Re: [hehchain/callo] définition du protocole de communication (#3)

@Tryptich j ai créé la branche "WIP#2" OU J AI INTRODUIT LE FICHIER MD CONSERNANT LA PREMIERE VERSION DU PROTOCOLE DE COMMUNICATION DANS LE RESEAU LIEN DU PROTOCOLE DE COMMUNICATION VERSION 1
