### ISSUE TITLE
interconnexion des noeuds

### ISSUE THREAD

**Issue by SteveRuben** [hehchain/callo#4]
définir quel type de topologie aura le réseau avec la possibilité de router le message d'un nœud à un autre. En d'autre terme comme fait pour que quelque soit la taille du réseau, la communication entre chaque nœud se fait en 6 sauts. Tu peux commencer par les hypercubes de taille 6. 
De même tu devra définir comment un nœud joins, quitte et rejoins le réseau et vérifier que le nœud qui rejoins le réseau ne soit pas un espion ou un hacker.

**Comment by feav** [comment]
> En d'autre terme comme fait pour que quelque soit la taille du réseau, la communication entre chaque nœud se fait en 6 sauts.

_Pour que ca se fasse en Maximum 6 sauts ou pour que ce se fasse en exactement 6 sauts?_

**Comment by SteveRuben** [comment]
@feav pour que ça se fasse en maximum 6 sauts.

**Comment by Tryptich** [comment]
@feav tu as déjà envoyé ton numéro à fabrice ?

**Comment by feav** [comment]
il y a un mail qui me demandait mon numéro, j'ai répondu en l'envoyant.

**Comment by feav** [comment]
@Tryptich il s'agit ici d'une tâche purement théorique?

**Comment by SteveRuben** [comment]
Oui

**Comment by SteveRuben** [comment]
Produit un cahier de conception

**Comment by SteveRuben** [comment]
Bonjour produit une documentation sur cette tache @feav.  ( un fichier d'extension md ).

**Comment by feav** [comment]
OK

**Comment by SteveRuben** [comment]
faut créer un branche avant de pousser par la suite.

**Comment by SteveRuben** [comment]
@feav il y a des manquements dans ton document bien que l'idée centrale y est. tu as abordé le problème en oubliant que nous sommes dans un réseau peer-to-peer et qu'il existe pas de serveur central ou du moins  pas conventionnellement, mais qu'il existe plutôt un registre ou une autre entité pareil.

**Comment by feav** [comment]
@thierrysup  

> comment se fera le processus d'authentification du nœud pour que celui ci intègre le réseau?
