### ISSUE TITLE
définition des algorithmes de sécurité

### ISSUE THREAD

**Issue by SteveRuben** [hehchain/callo#5]
choix et implémentation des algorithmes de chiffrage et de déchiffrage. Nous utiliserons la cryptographie asymétrique. Ainsi tu peux utiliser soit Hiellman soit les courbes elliptique ( de préférences ce dernier). Notons ici que le temps de chiffrement et de déchiffrement doit être inférieur à 5 secondes.

Nous te recommandons celui-ci pour point de départ [cyph](https://github.com/cyph/cyph)

**Comment by SteveRuben** [comment]
produire une documentation ( un ficher d'extension md) @thierrysup

**Comment by thierrysup** [comment]
hello if some issues exist in previous commit about security algorithms ... share it with me .
waiting next...

**Comment by SteveRuben** [comment]
http://www.christian-faure.net/2015/09/13/la-blockchain-et-lemergence-des-distributed-consensus-engines/
